# Statically link the MSVC CRT so nutils.exe is a single self-contained binary
# with no vcruntime/redistributable dependency.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
